[package]
name = "pi_3d"
version = "0.0.1"
authors = ["baip0002 <2494156981@qq.com>"]
edition = "2021"
description = "3D Framework for Scene."
repository = "https://github.com/GaiaWorld/pi_3d"
license = "MIT OR Apache-2.0"
keywords = ["3d scene"]

[workspace]
members = ["crates/*"]

[dependencies]
pi_scene_context = { path = "crates/pi_scene_context" }
pi_engine_shell = { path = "crates/pi_engine_shell" }
default_render = { path = "crates/default_render" }
material_textures = { path = "crates/material_textures" }
skybox = { path = "crates/skybox" }
procedural_texture = { path = "crates/procedural_texture" }
skeletons = { path = "crates/skeletons" }

unlit_material = { path = "crates/unlit_material" }
# standard_material = { path = "crates/standard_material" }
render_resource = { path = "../pi_render/crates/render_resource" }
# pi_scene_math = { git = "https://github.com/GaiaWorld/pi_scene" }
pi_scene_math = { path = "../pi_scene/crates/pi_scene_math" }
# pi_render = { git = "https://github.com/GaiaWorld/pi_render" }
pi_render = { path = "../pi_render" }

pi_ecs_macros = { git = "https://github.com/GaiaWorld/pi_ecs.git" }
pi_ecs_utils = { git = "https://github.com/GaiaWorld/pi_ecs_utils.git" }
pi_ecs = { git = "https://github.com/GaiaWorld/pi_ecs.git" }

wgpu = "0.13"
env_logger = "0.9"
log = "0.4"
smallvec = "1.9"
crossbeam="0.8"
futures = "0.3"

[[example]]
name = "cube"
path = "examples/cube/cube.rs"

[[example]]
name = "unlit_cube"
path = "examples/cube/unlit_cube.rs"

[[example]]
name = "quad"
path = "examples/quad/quad.rs"

[[example]]
name = "skybox"
path = "examples/skybox/skybox.rs"

[[example]]
name = "performance_static_render"
path = "examples/performance/static_10000.rs"

[[example]]
name = "performance_transform_render"
path = "examples/performance/transform_10000.rs"

[[example]]
name = "oct_tree"
path = "examples/oct_tree/oct_tree.rs"

[[example]]
name = "noise"
path = "examples/ball/ball.rs"

[[example]]
name = "cloud"
path = "examples/procedural_texture/cloud.rs"

[[example]]
name = "water"
path = "examples/procedural_texture/water.rs"

[[example]]
name = "brdf"
path = "examples/procedural_texture/brdf.rs"

[[example]]
name = "skeletons"
path = "examples/skeletons/skeletons.rs"